#Config Server
#spring:
#  application:
#    name: gateway-service
#  config:
#    import: configserver:http://localhost:8888

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/booking/**
        - id: flight-management-service
          uri: lb://flight-management-service
          predicates:
            - Path=/flight/**
        - id: user-management-service
          uri: lb://user-management-service
          predicates:
            - Path=/user/**

server:
  port: 7100
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost